#!/usr/bin/env bash
#
# Provision the per-customer config for a single-tenant hosted nable instance.
# Hand-cranked: this generates the instance's .env (a stable instance id + the
# derived control-plane secret + the domain) so the getnable.com account can mint
# a one-click login into it. You still launch the EC2 box and deploy yourself,
# see docs/PROVISIONING.md for the full walkthrough.
#
# Usage:
#   CP_MASTER_SECRET=<master> ./deploy/provision-tenant.sh <customer-slug> <domain>
#
# Example:
#   CP_MASTER_SECRET=$(cat ~/.nable/cp_master_secret) \
#     ./deploy/provision-tenant.sh baptist baptist.getnable.com
#
set -euo pipefail

SLUG="${1:-}"
DOMAIN="${2:-}"
if [ -z "$SLUG" ] || [ -z "$DOMAIN" ]; then
  echo "usage: CP_MASTER_SECRET=... $0 <customer-slug> <domain>" >&2
  exit 2
fi
if [ -z "${CP_MASTER_SECRET:-}" ]; then
  echo "error: set CP_MASTER_SECRET (the same master the getnable.com account uses)" >&2
  exit 2
fi
if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required (for the HMAC secret derivation)" >&2
  exit 1
fi

# Stable, human-readable instance id. It must match what you register for this
# customer in the getnable.com account so login routes to the right box.
INSTANCE_ID="$SLUG"

# Derive the per-instance secret EXACTLY as web/api/account/dashboard-login.js and
# control_plane.py expect: hmac_sha256_hex(CP_MASTER_SECRET, "nable-instance:"+id).
DERIVED="$(printf '%s' "nable-instance:${INSTANCE_ID}" \
  | openssl dgst -sha256 -hmac "${CP_MASTER_SECRET}" | awk '{print $NF}')"

# A strong fallback dashboard password (used only if the customer has no SSO).
DASH_PW="$(openssl rand -hex 24)"

mkdir -p tenants
OUT="tenants/${SLUG}.env"
umask 077
cat > "$OUT" <<ENV
# nable single-tenant instance — ${SLUG}
# Generated by deploy/provision-tenant.sh. SECRET FILE: chmod 600, never commit.
DOMAIN=${DOMAIN}

# Hosted control-plane login (one-click from the getnable.com account)
FINOPS_INSTANCE_ID=${INSTANCE_ID}
FINOPS_CONTROL_PLANE_SECRET=${DERIVED}

# Auth: require a login, with a generated password fallback. Prefer the
# customer's SSO when they have one (uncomment + fill the FINOPS_SSO_* block).
FINOPS_REQUIRE_AUTH=1
FINOPS_DASHBOARD_PASSWORD=${DASH_PW}
FINOPS_ENABLE_SCHEDULER=1
# FINOPS_SSO_ISSUER=
# FINOPS_SSO_CLIENT_ID=
# FINOPS_SSO_CLIENT_SECRET=
# FINOPS_SSO_REDIRECT_URI=https://${DOMAIN}/sso/callback
# FINOPS_SSO_ALLOWED_DOMAINS=

# The customer's READ-ONLY cloud credentials (single-tenant, never pooled).
# Easiest: hand them the one-click CloudFormation read-only key (finops setup aws)
# and paste the outputs here.
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_DEFAULT_REGION=us-east-1
ENV

echo "Wrote ${OUT} (chmod 600)."
echo
echo "1. Register this instance in the getnable.com account so login routes to it:"
echo "     instance_id     = ${INSTANCE_ID}"
echo "     instance_domain = ${DOMAIN}"
echo "2. Launch the EC2 box and copy ${OUT} to it as .env (see docs/PROVISIONING.md)."
echo "3. On the box:  docker compose --profile tls up -d"
echo
echo "The customer then logs in at https://getnable.com/account -> Open my dashboard,"
echo "which mints a one-click token into https://${DOMAIN}."
