#!/usr/bin/env bash
#
# Provision the per-customer config for a single-tenant hosted nable instance.
# Hand-cranked: this generates the instance's .env (a stable instance id + the
# derived control-plane secret + the domain) so the getnable.com account can mint
# a one-click login into it. You still launch the EC2 box and deploy yourself,
# see docs/PROVISIONING.md for the full walkthrough.
#
# Usage:
#   CP_MASTER_SECRET=<master> ./deploy/provision-tenant.sh <customer-slug> <domain>
#
# Example:
#   CP_MASTER_SECRET=$(cat ~/.nable/cp_master_secret) \
#     ./deploy/provision-tenant.sh baptist baptist.getnable.com
#
set -euo pipefail

SLUG="${1:-}"
DOMAIN="${2:-}"
if [ -z "$SLUG" ] || [ -z "$DOMAIN" ]; then
  echo "usage: CP_MASTER_SECRET=... $0 <customer-slug> <domain>" >&2
  exit 2
fi
if [ -z "${CP_MASTER_SECRET:-}" ]; then
  echo "error: set CP_MASTER_SECRET (the same master the getnable.com account uses)" >&2
  exit 2
fi
if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required (for the HMAC secret derivation)" >&2
  exit 1
fi

# Validate inputs before they reach a filename or the .env body. A slug with "/"
# or ".." would write the secret file outside tenants/ (dodging the gitignore),
# and a newline in either arg would inject extra lines into the .env. Anchored
# bash regex rejects both (the classes exclude "/", "." for the slug, and \n).
if [[ ! "$SLUG" =~ ^[a-z0-9][a-z0-9-]{0,40}$ ]]; then
  echo "error: slug must be lowercase letters, digits, hyphens (1-41 chars); got: $SLUG" >&2
  exit 2
fi
if [[ ! "$DOMAIN" =~ ^[a-z0-9]([a-z0-9.-]{0,251}[a-z0-9])?$ ]]; then
  echo "error: domain must be a valid hostname; got: $DOMAIN" >&2
  exit 2
fi

# Stable, human-readable instance id. It must match what you register for this
# customer in the getnable.com account so login routes to the right box.
INSTANCE_ID="$SLUG"

# Derive the per-instance secret EXACTLY as web/api/account/dashboard-login.js and
# control_plane.py expect: hmac_sha256_hex(CP_MASTER_SECRET, "nable-instance:"+id).
DERIVED="$(printf '%s' "nable-instance:${INSTANCE_ID}" \
  | openssl dgst -sha256 -hmac "${CP_MASTER_SECRET}" | awk '{print $NF}')"

# A strong fallback dashboard password (used only if the customer has no SSO).
DASH_PW="$(openssl rand -hex 24)"

# Seed a Postgres password. The compose file's optional postgres service requires
# the variable to exist even though single-tenant uses SQLite, so this keeps the
# deploy from failing to parse the compose file.
PG_PW="$(openssl rand -hex 16)"

# Vault master key (URL-safe base64 Fernet key). It goes in THIS .env on the host
# root volume, never inside the /data volume that holds the encrypted vault.db, so
# a leaked or snapshotted data volume can't be decrypted on its own. Keep it
# constant for the life of the box: rotating it orphans every stored credential.
if command -v python3 >/dev/null 2>&1; then
  VAULT_KEY="$(python3 -c 'import base64,os;print(base64.urlsafe_b64encode(os.urandom(32)).decode())')"
else
  # Fernet requires URL-safe base64 (-_ instead of +/); translate openssl's output.
  VAULT_KEY="$(openssl rand 32 | openssl base64 -A | tr '+/' '-_')"
fi

mkdir -p tenants
OUT="tenants/${SLUG}.env"
umask 077
cat > "$OUT" <<ENV
# nable single-tenant instance — ${SLUG}
# Generated by deploy/provision-tenant.sh. SECRET FILE: chmod 600, never commit.
DOMAIN=${DOMAIN}

# Hosted control-plane login (one-click from the getnable.com account)
FINOPS_INSTANCE_ID=${INSTANCE_ID}
FINOPS_CONTROL_PLANE_SECRET=${DERIVED}

# Auth: require a login, with a generated password fallback. Prefer the
# customer's SSO when they have one (uncomment + fill the FINOPS_SSO_* block).
FINOPS_REQUIRE_AUTH=1
FINOPS_DASHBOARD_PASSWORD=${DASH_PW}
FINOPS_ENABLE_SCHEDULER=1

# Credential vault master key, kept here on the host and off the /data volume.
FINOPS_VAULT_KEY=${VAULT_KEY}

# Required so the compose file's optional postgres service parses. Single-tenant
# uses SQLite; this is only consumed if you switch on shared Postgres.
POSTGRES_PASSWORD=${PG_PW}
# FINOPS_SSO_ISSUER=
# FINOPS_SSO_CLIENT_ID=
# FINOPS_SSO_CLIENT_SECRET=
# FINOPS_SSO_REDIRECT_URI=https://${DOMAIN}/sso/callback
# FINOPS_SSO_ALLOWED_DOMAINS=

# The customer's READ-ONLY cloud credentials (single-tenant, never pooled).
# Easiest: hand them the one-click CloudFormation read-only key (finops setup aws)
# and paste the outputs here.
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_DEFAULT_REGION=us-east-1
ENV
# umask only sets the mode on CREATION; an explicit chmod also locks down a
# pre-existing file when re-provisioning (rotating the secret, fixing a domain).
chmod 600 "$OUT"

echo "Wrote ${OUT} (chmod 600)."
echo
echo "1. Register this instance in the getnable.com account so login routes to it:"
echo "     instance_id     = ${INSTANCE_ID}"
echo "     instance_domain = ${DOMAIN}"
echo "2. Launch the EC2 box and copy ${OUT} to it as .env (see docs/PROVISIONING.md)."
echo "3. On the box:  docker compose --profile tls up -d --build"
echo
echo "The customer then logs in at https://getnable.com/account -> Open my dashboard,"
echo "which mints a one-click token into https://${DOMAIN}."
