#!/usr/bin/env python3
"""
nable budget check entrypoint for GitHub Actions.
Reads budget.yml, checks actual spend, writes PR comment and exit signal.
"""
from __future__ import annotations

import json
import os
import sys
from datetime import date
from pathlib import Path

# Load env
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

budget_yaml = os.environ.get("INPUT_BUDGET_YAML_PATH", "budget.yml")
fail_on_exceeded = os.environ.get("INPUT_FAIL_ON_EXCEEDED", "true").lower() == "true"

try:
    from finops.budget.enforcer import check_all_budgets, sync_from_yaml
except ImportError:
    print("finops-mcp not installed correctly")
    sys.exit(0)

# Sync budgets from YAML if file exists
if Path(budget_yaml).exists():
    result = sync_from_yaml(budget_yaml)
    print(f"Loaded budgets: {result.get('total', 0)} from {budget_yaml}")

results = check_all_budgets()

if not results:
    print("✅ No budgets configured — skipping budget gate")
    _comment = f"""<!-- nable-budget-comment -->
## 💰 nable Budget Check

✅ **No budgets configured.** Add a `budget.yml` to your repo to track spending limits.

```yaml
budgets:
  - name: AWS Monthly
    scope_type: provider
    scope_value: aws
    period: monthly
    limit_usd: 50000
    alert_at_pct: 80
```

_Generated by [nable FinOps](https://github.com/nable-finops/nable) · {date.today().isoformat()}_
"""
    Path("/tmp/nable-budget-comment.md").write_text(_comment)
    sys.exit(0)

# Build status
exceeded = [b for b in results if b["status"] == "exceeded"]
warnings  = [b for b in results if b["status"] == "warning"]
ok_list   = [b for b in results if b["status"] == "ok"]

# Console output
print(f"\n{'─'*60}")
print(f"  nable Budget Check — {date.today().isoformat()}")
print(f"{'─'*60}")
for b in results:
    icon = "❌" if b["status"] == "exceeded" else "⚠️ " if b["status"] == "warning" else "✅"
    bar_filled = int(b["pct_used"] / 100 * 20)
    bar = "█" * min(bar_filled, 20) + "░" * (20 - min(bar_filled, 20))
    print(f"  {icon} {b['name']}")
    print(f"     [{bar}] {b['pct_used']:.0f}% — ${b['spent']:,.0f} / ${b['limit']:,.0f}")
print(f"{'─'*60}")
print(f"  {len(ok_list)} OK · {len(warnings)} warnings · {len(exceeded)} exceeded")
print(f"{'─'*60}\n")

# PR comment
status_header = (
    "🔴 **Budget exceeded** — action required!"
    if exceeded else
    "🟡 **Budget warning** — approaching limit"
    if warnings else
    "✅ **All budgets on track**"
)

rows = []
for b in results:
    status_icon = "🔴" if b["status"] == "exceeded" else "🟡" if b["status"] == "warning" else "✅"
    bar_filled = int(b["pct_used"] / 100 * 10)
    bar = "█" * min(bar_filled, 10) + "░" * (10 - min(bar_filled, 10))
    projected = f" (run rate: ${b.get('run_rate_monthly', 0):,.0f})" if b["status"] != "ok" else ""
    rows.append(
        f"| {status_icon} {b['name']} | `{b['scope_type']}={b['scope_value']}` "
        f"| ${b['spent']:,.0f} | ${b['limit']:,.0f} | {b['pct_used']:.0f}% `{bar}`{projected} |"
    )

table = "\n".join(rows)

comment = f"""<!-- nable-budget-comment -->
## 💰 nable Budget Check

{status_header}

| Budget | Scope | Spent | Limit | Usage |
|--------|-------|------:|------:|-------|
{table}

"""

if exceeded:
    comment += "### ❌ Exceeded budgets require attention\n"
    for b in exceeded:
        overage = b["spent"] - b["limit"]
        comment += f"- **{b['name']}**: ${overage:,.0f} over limit. Check top services and recent deployments.\n"
    comment += "\n"

if warnings:
    comment += "### ⚠️ Budgets approaching limit\n"
    for b in warnings:
        remaining = b["limit"] - b["spent"]
        comment += f"- **{b['name']}**: ${remaining:,.0f} remaining ({100 - b['pct_used']:.0f}%)\n"
    comment += "\n"

comment += f"_Generated by [nable FinOps](https://github.com/nable-finops/nable) · {date.today().isoformat()}_\n"

Path("/tmp/nable-budget-comment.md").write_text(comment)

if exceeded and fail_on_exceeded:
    exceeded_names = [b["name"] for b in exceeded]
    Path("/tmp/nable-budget-exceeded").write_text(
        f"Exceeded budgets: {', '.join(exceeded_names)}\n"
    )
    print(f"::error::Budget gate failed: {', '.join(exceeded_names)}")
    # Don't exit here — the action.yml step handles the failure signal
