"""
End-to-end rightsizing remediation via Terraform PR.

Flow:
  1. Load open rightsizing recommendations from the DB (by ID or all open).
  2. For each rec, resolve the Terraform resource in the IaC repo.
  3. Patch the instance_type / instance_class in the .tf file on disk.
  4. Create a git branch, commit, push.
  5. Open a GitHub PR with a cost impact summary.
  6. Mark recommendations as acted_on, storing the PR URL.

Supported resource types:
  aws_instance, aws_db_instance, aws_rds_cluster_instance,
  aws_elasticache_cluster, aws_elasticache_replication_group, aws_redshift_cluster

Each recommendation must carry recommended_config with:
  - instance_type  (or instance_class / node_type depending on resource type)
  - tf_resource_type   e.g. "aws_instance"
  - tf_resource_name   e.g. "api_server"
  - from_instance_type (the current type, for PR description)
"""
from __future__ import annotations

import json
import logging
import subprocess
from pathlib import Path
from typing import Any

from sqlalchemy import select

from ..storage.db import get_engine, savings_recommendations
from ..recommendations.savings_tracker import mark_acted_on
from ..tagging.hcl_patcher import (
    find_resource_file,
    apply_rightsizing_fix,
    generate_rightsizing_diff,
)
from ..tagging.tf_state import build_id_map, resolve_recommendation
from ..integrations.ticketing import create_github_pr

log = logging.getLogger(__name__)


# ── Git helper ────────────────────────────────────────────────────────────────

def _git(tf_dir: str, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=tf_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} failed: {result.stderr.strip()}"
        )
    return result.stdout.strip()


# ── PR body ───────────────────────────────────────────────────────────────────

def _pr_body(recs: list[dict]) -> str:
    total_monthly = sum(r["estimated_monthly_savings_usd"] for r in recs)
    total_annual = total_monthly * 12

    lines = []
    for r in recs:
        rec_cfg = r["recommended_config"]
        from_type = rec_cfg.get("from_instance_type", "?")
        to_type = (
            rec_cfg.get("instance_type")
            or rec_cfg.get("instance_class")
            or rec_cfg.get("node_type")
            or "?"
        )
        tf_addr = f"{rec_cfg.get('tf_resource_type', '?')}.{rec_cfg.get('tf_resource_name', r['resource_name'])}"
        saving = r["estimated_monthly_savings_usd"]
        lines.append(
            f"| `{tf_addr}` | `{from_type}` | `{to_type}` | ${saving:,.0f}/mo |"
        )

    table = (
        "| Resource | Current type | Recommended | Saving |\n"
        "|----------|-------------|-------------|--------|\n"
        + "\n".join(lines)
    )

    return (
        f"## Rightsizing changes\n\n"
        f"Applies {len(recs)} instance type change(s) identified by nable.\n\n"
        f"{table}\n\n"
        f"**Total estimated saving: ${total_monthly:,.0f}/mo (${total_annual:,.0f}/yr)**\n\n"
        f"### What to do after merging\n\n"
        f"1. Review plan: `terraform plan`\n"
        f"2. If plan looks correct: `terraform apply`\n"
        f"3. nable will auto-verify the change and record realized savings within 24h.\n\n"
        f"---\n"
        f"Generated by [nable FinOps MCP](https://getnable.com)"
    )


# ── Main entry point ──────────────────────────────────────────────────────────

def open_rightsizing_pr(
    tf_dir: str,
    github_repo: str | None = None,
    recommendation_ids: list[int] | None = None,
    resource_overrides: list[dict] | None = None,
    branch: str = "fix/rightsizing",
    base_branch: str = "main",
    pr_title: str | None = None,
    dry_run: bool = False,
    patch_only: bool = False,
) -> dict[str, Any]:
    """
    Patch Terraform files for open rightsizing recommendations and open a GitHub PR.

    Resolution order for each recommendation:
      1. Terraform state (terraform.tfstate or `terraform show -json`) — automatic
      2. resource_overrides parameter — manual fallback
      3. recommended_config stored in DB — if previously set

    Args:
        tf_dir:              Path to the Terraform working directory.
        github_repo:         "owner/repo" for the GitHub PR. Optional when patch_only=True.
        recommendation_ids:  IDs to act on. If None, uses all open rightsizing recs.
        resource_overrides:  Manual mapping fallback when state resolution fails.
                             Each entry: {recommendation_id, tf_resource_type, tf_resource_name}.
        branch:              Git branch to create. Defaults to "fix/rightsizing".
        base_branch:         PR target branch. Defaults to "main".
        pr_title:            PR title. Auto-generated if not provided.
        dry_run:             Show diffs without writing files or creating the PR.
        patch_only:          Write files locally but skip git and GitHub PR creation.
                             Useful when the user manages their own git workflow.

    Returns a dict with pr_url, files_modified, recommendations_acted_on, and any errors.
    """
    engine = get_engine()

    # 1. Load recommendations
    q = select(savings_recommendations).where(
        savings_recommendations.c.source == "rightsizing",
        savings_recommendations.c.status == "open",
    )
    if recommendation_ids:
        q = q.where(savings_recommendations.c.id.in_(recommendation_ids))

    with engine.connect() as conn:
        rows = conn.execute(q).fetchall()

    if not rows:
        return {
            "error": "No open rightsizing recommendations found. Run get_rightsizing_recommendations first.",
            "pr_url": None,
        }

    # Build override lookup: recommendation_id -> {tf_resource_type, tf_resource_name}
    override_map: dict[int, dict] = {}
    for ov in (resource_overrides or []):
        rid = ov.get("recommendation_id")
        if rid is not None:
            override_map[int(rid)] = ov

    # Pre-build Terraform state ID map once (avoids re-reading state per rec)
    state_id_map: dict[str, dict] = {}
    state_load_error: str = ""
    try:
        state_id_map = build_id_map(tf_dir)
        log.info("Loaded Terraform state: %d resources indexed", len(state_id_map))
    except RuntimeError as exc:
        state_load_error = str(exc)
        log.info("Terraform state not available (%s) — will use manual overrides", exc)

    recs: list[dict] = []
    skipped: list[dict] = []

    for row in rows:
        rec_cfg = json.loads(row.recommended_config or "{}")

        # Resolution order:
        # 1. Terraform state (auto, using cloud resource ID)
        # 2. resource_overrides (manual)
        # 3. recommended_config stored in DB (if previously set)
        override = override_map.get(row.id, {})

        state_match = resolve_recommendation(
            tf_dir,
            resource_id=row.resource_id,
            resource_name=row.resource_name,
            id_map=state_id_map or None,
        ) if state_id_map else None

        tf_resource_type = (
            state_match.get("tf_resource_type") if state_match else None
            or override.get("tf_resource_type")
            or rec_cfg.get("tf_resource_type", "")
        )
        tf_resource_name = (
            state_match.get("tf_resource_name") if state_match else None
            or override.get("tf_resource_name")
            or rec_cfg.get("tf_resource_name", "")
        )

        if not tf_resource_type or not tf_resource_name:
            if state_load_error:
                reason = (
                    f"No Terraform state found in {tf_dir} ({state_load_error}). Run this from "
                    f"your IaC directory (where terraform.tfstate or `terraform show -json` is "
                    f"available), or pass resource_overrides to map this recommendation to its "
                    f".tf address."
                )
            else:
                reason = (
                    f"Resource {row.resource_id} is not managed in this Terraform state. If it "
                    f"lives in another module or repo, pass a resource_override mapping it to its "
                    f"tf_resource_type/tf_resource_name."
                )
            skipped.append({"id": row.id, "resource_id": row.resource_id, "reason": reason})
            continue

        # Resolve new instance type value (attribute name varies by resource type)
        new_value = (
            rec_cfg.get("instance_type")
            or rec_cfg.get("instance_class")
            or rec_cfg.get("node_type")
        )
        if not new_value:
            skipped.append({
                "id": row.id,
                "resource_id": row.resource_id,
                "reason": "No instance_type / instance_class / node_type in recommended_config.",
            })
            continue

        # Find the .tf file that declares this resource
        file_path = find_resource_file(tf_dir, tf_resource_type, tf_resource_name)
        if not file_path:
            skipped.append({
                "id": row.id,
                "resource_id": row.resource_id,
                "reason": f"Could not find resource {tf_resource_type}.{tf_resource_name} in {tf_dir}",
            })
            continue

        recs.append({
            "id": row.id,
            "resource_id": row.resource_id,
            "resource_name": row.resource_name,
            "estimated_monthly_savings_usd": row.estimated_monthly_savings_usd or 0.0,
            "file_path": file_path,
            "tf_resource_type": tf_resource_type,
            "tf_resource_name": tf_resource_name,
            "new_value": new_value,
            "recommended_config": rec_cfg,
        })

    if not recs:
        return {
            "error": "No patchable recommendations. All recs are missing Terraform resource info.",
            "skipped": skipped,
            "pr_url": None,
        }

    # 2. Dry-run: return diffs only
    if dry_run:
        diffs = {}
        for r in recs:
            diff = generate_rightsizing_diff(
                r["file_path"], r["tf_resource_type"], r["tf_resource_name"], r["new_value"]
            )
            if diff:
                diffs[r["file_path"]] = diff
        return {
            "dry_run": True,
            "patchable": len(recs),
            "skipped": skipped,
            "diffs": diffs,
            "estimated_monthly_savings_usd": sum(r["estimated_monthly_savings_usd"] for r in recs),
        }

    # 3. Apply patches to disk
    modified_files: list[str] = []
    patch_errors: list[dict] = []

    for r in recs:
        try:
            changed = apply_rightsizing_fix(
                r["file_path"], r["tf_resource_type"], r["tf_resource_name"], r["new_value"]
            )
            if changed and r["file_path"] not in modified_files:
                modified_files.append(r["file_path"])
        except Exception as exc:
            patch_errors.append({"id": r["id"], "file": r["file_path"], "error": str(exc)})

    if not modified_files:
        return {
            "error": "No files were modified. Resource declarations may already be at the recommended type.",
            "skipped": skipped,
            "patch_errors": patch_errors,
            "pr_url": None,
        }

    total_saving = sum(r["estimated_monthly_savings_usd"] for r in recs)

    # 4. patch_only: skip git and GitHub, just return patched files
    if patch_only:
        acted_on_ids = []
        for r in recs:
            if mark_acted_on(r["id"]):
                acted_on_ids.append(r["id"])
        return {
            "patch_only": True,
            "files_modified": modified_files,
            "recommendations_acted_on": acted_on_ids,
            "estimated_monthly_savings_usd": total_saving,
            "estimated_annual_savings_usd": total_saving * 12,
            "skipped": skipped,
            "patch_errors": patch_errors,
            "next_step": "Review the changes, then run `terraform plan` to verify the cost delta before applying.",
        }

    # 5. Git: create branch, stage, commit, push
    try:
        _git(tf_dir, "checkout", "-b", branch)
        _git(tf_dir, "add", "--", *modified_files)
        n = len(recs)
        _git(
            tf_dir,
            "commit", "-m",
            f"fix(rightsizing): downsize {n} instance(s), save ~${total_saving:,.0f}/mo\n\n"
            f"Applied nable rightsizing recommendations.\n"
            f"Estimated annual saving: ~${total_saving * 12:,.0f}\n\n"
            f"Co-Authored-By: nable FinOps MCP <noreply@getnable.com>",
        )
        _git(tf_dir, "push", "-u", "origin", branch)
    except RuntimeError as exc:
        return {
            "error": f"Git operation failed: {exc}",
            "files_modified": modified_files,
            "branch": branch,
            "pr_url": None,
        }

    # 6. Open GitHub PR (requires github_repo)
    pr_url = ""
    if github_repo:
        title = pr_title or (
            f"fix(rightsizing): downsize {len(recs)} instance(s), "
            f"save ~${total_saving:,.0f}/mo"
        )
        try:
            pr_resp = create_github_pr(
                repo=github_repo,
                title=title,
                body=_pr_body(recs),
                head=branch,
                base=base_branch,
            )
            pr_url = pr_resp.get("html_url", "")
        except Exception as exc:
            return {
                "error": f"PR creation failed: {exc}",
                "files_modified": modified_files,
                "branch": branch,
                "pr_url": None,
            }

    # 7. Mark recommendations as acted_on
    acted_on_ids = []
    for r in recs:
        if mark_acted_on(r["id"]):
            acted_on_ids.append(r["id"])

    return {
        "pr_url": pr_url or None,
        "branch": branch,
        "files_modified": modified_files,
        "recommendations_acted_on": acted_on_ids,
        "estimated_monthly_savings_usd": total_saving,
        "estimated_annual_savings_usd": total_saving * 12,
        "skipped": skipped,
        "patch_errors": patch_errors,
    }
